### ISSUE TITLE
Ingress publish with QoS 2 could deliver twice.

### ISSUE THREAD

**Issue by LiamBindle** [LiamBindle/mqtt-client#5]
In `__mqtt_recv` the `MQTT_CONTROL_PUBLISH` case of the big switch statement needs a mechanism for ensuring that QoS 2 publishes are not passed to the callback more than once.

This could be accomplished by looping through the message queue and checking for messages with the same packet ID.

**Comment by amasmiller** [comment]
It appears there is still a comment in `mqtt.c` implying QOS-2 may not be completely followed, w.r.t. duplicates.

https://github.com/LiamBindle/MQTT-C/blob/master/src/mqtt.c#L521

Can I trust that MQTT-C will follow in-order (and non-duplicated) messaging, as described in:

https://stackoverflow.com/questions/30955110/is-message-order-preserved-in-mqtt-messages

?

Thanks.  MQTT-C is a very easy to use, and is an excellent API.

**Comment by LiamBindle** [comment]
Hi, sorry I just saw this. Yeah sorry, I just forgot to remove that comment.

Actually no, currently QoS 2 will deliver exactly once but the ordering is not guaranteed (but it should be). I will try to get to this weekend. I've created a new issue (#9) so keep an eye on that.

**Comment by amasmiller** [comment]
Excellent!  I'll keep an eye on #9.
